// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqKZWyCDgOPaf4D1HS5pkySZoOmcIJPZQ',
    appId: '1:317133576524:web:c64151065089ed35d357e9',
    messagingSenderId: '317133576524',
    projectId: 'authcoffeeshop',
    authDomain: 'authcoffeeshop.firebaseapp.com',
    storageBucket: 'authcoffeeshop.appspot.com',
    measurementId: 'G-29ZP73LNE3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBERHD6lRf4PFs5FC6eIojpuQecjSFAO5c',
    appId: '1:317133576524:android:866d4079da7fe68dd357e9',
    messagingSenderId: '317133576524',
    projectId: 'authcoffeeshop',
    storageBucket: 'authcoffeeshop.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDN2OeEXXmImwwmsX2pMXH5BdItp5TLjww',
    appId: '1:317133576524:ios:0afc432e8063fa72d357e9',
    messagingSenderId: '317133576524',
    projectId: 'authcoffeeshop',
    storageBucket: 'authcoffeeshop.appspot.com',
    iosClientId: '317133576524-je8qkfojlao4jhvtsjd8bh7rvqa457td.apps.googleusercontent.com',
    iosBundleId: 'com.example.coffeeShopApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDN2OeEXXmImwwmsX2pMXH5BdItp5TLjww',
    appId: '1:317133576524:ios:87fbc85b896a2e17d357e9',
    messagingSenderId: '317133576524',
    projectId: 'authcoffeeshop',
    storageBucket: 'authcoffeeshop.appspot.com',
    iosClientId: '317133576524-3i94grnvfevsgh4uqtf6qog474bf8vd3.apps.googleusercontent.com',
    iosBundleId: 'com.example.coffeeShopApp.RunnerTests',
  );
}
